# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2019
  project: Static Info Tables (dpl
  version: 6
  release: 6.7.4
  latex_documents:
  - - Index
    - static_info_tables_pl.tex
    - Static Info Tables (pl)
    - Łukasz Uznański
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
